---
- name: "Install dependencies as root: {{ SOLR_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ SOLR_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
- name: "Install dependencies as user {{ SOLR_USER }}: {{ SOLR_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ SOLR_DEPENDENCIES }}"
  when: INSTALL_DEPENDENCIES.failed
- name: Check if javac command exists
  stat:
    path: /usr/bin/javac
  register: JAVAC_EXISTS
- name: Download dir to ~ when platform is not Apple
  set_fact:
    SOLR_DOWNLOAD_DEST: ~/"{{ SOLR_DOWNLOAD_FILENAME }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Check for the {{ SOLR_NAME }} download
  stat:
    path: "{{ SOLR_DOWNLOAD_DEST }}"
  register: SOLR_DOWNLOAD
- name: Download the Solr binary
  get_url:
    url: "{{ SOLR_DOWNLOAD_URL }}"
    dest: "{{ SOLR_DOWNLOAD_DEST }}"
  when: not SOLR_DOWNLOAD.stat.exists
- name: Create the computate source directory {{ COMPUTATE_SRC }}
  file:
    name: "{{ COMPUTATE_SRC }}"
    state: directory
- name: Check for the computate pom.xml
  stat:
    path: "{{ COMPUTATE_SRC }}/pom.xml"
  register: computate_pom
- name: Clone the computate source code
  git:
    repo: "{{ COMPUTATE_REPO }}"
    dest: "{{ COMPUTATE_SRC }}"
  when: not computate_pom.stat.exists
- name: Create the {{ SOLR_NAME }} install directory {{ SOLR_OPT }}. 
  file:
    name: "{{ SOLR_OPT }}"
    state: directory
- name: Install {{ SOLR_NAME }} into the {{ SOLR_OPT }} install directory. 
  unarchive:
    src: "{{ SOLR_DOWNLOAD_DEST }}"
    dest: "{{ SOLR_OPT }}"
    remote_src: true
    extra_opts: [--strip-components=1]
- name: Create the {{ SOLR_NAME }} data directory {{ SOLR_DATA }}. 
  file:
    name: "{{ SOLR_DATA }}"
    state: directory
    mode: 0777
#- name: set SELinux permissions on {{ SOLR_DATA }}
#  sefcontext:
#    target: "{{ SOLR_DATA }}"
#    setype: container_file_t
#  become: true
#  vars:
#    ansible_python_interpreter: "{{ SOLR_PYTHON }}"
#  when: SOLR_USE_PODMAN
#- name: reload SELinux policy to ensure that {{ SOLR_NAME }} is executable
#  command: "restorecon -irv {{ SOLR_DATA }}"
#  become: true
#  when: SOLR_USE_PODMAN
- name: Copy the solr.xml to the {{ SOLR_NAME }} directory {{ SOLR_DATA }}. 
  copy:
    src: "{{ SOLR_OPT }}/server/solr/solr.xml"
    dest: "{{ SOLR_DATA }}/solr.xml"
    remote_src: true
- name: Delete the example directory {{ SOLR_OPT }}/example. 
  file:
    name: "{{ SOLR_OPT }}/example"
    state: absent
- name: Link the computate configset into {{ SOLR_NAME }}. 
  file:
    src: "{{ COMPUTATE_SRC }}/config/solr/server/solr/configsets/computate"
    dest: "{{ SOLR_OPT }}/server/solr/configsets/computate"
    state: link
- name: Find the {{ SOLR_NAME }} binaries in {{ SOLR_OPT }}/bin. 
  find:
    paths: "{{ SOLR_OPT }}/bin"
    recurse: no
  register: BIN_FILES
- name: Make the {{ SOLR_NAME }} binaries executable in {{ SOLR_OPT }}/bin. 
  file:
    dest: "{{item.path}}"
    mode: a+x
  with_items:
    - "{{BIN_FILES.files}}"
- name: Find the {{ SOLR_NAME }} cloud scripts in {{ SOLR_OPT }}/server/scripts/cloud-scripts. 
  find:
    paths: "{{ SOLR_OPT }}/server/scripts/cloud-scripts"
    recurse: no
  register: CLOUD_SCRIPTS
- name: Make the {{ SOLR_NAME }} cloud scripts executable in {{ SOLR_OPT }}/server/scripts/cloud-scripts. 
  file:
    dest: "{{item.path}}"
    mode: a+x
  with_items:
    - "{{CLOUD_SCRIPTS.files}}"
- name: Create the {{ SOLR_NAME }} systemd service {{ SOLR_SYSTEMD }}. 
  template:
    src: solr_service.j2
    dest: "{{ SOLR_SYSTEMD }}"
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Reload the services. 
  systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 else 'user' }}"
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Start and enable the {{ SOLR_NAME }} service. 
  service:
    name: "{{ SOLR_SERVICE }}"
    enabled: true
    state: restarted
    scope: "{{ 'system' if ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 else 'user' }}"
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
  when: ansible_pkg_mgr != 'homebrew'
- name: Create the {{ SOLR_NAME }} launchd service.
  template:
    src: solr_launchd_service.j2
    dest: "~/Library/LaunchAgents/org.solr.plist"
  when: ansible_pkg_mgr == 'homebrew'
- name: Load the {{ SOLR_NAME }} launchd service.
  shell: launchctl load ~/Library/LaunchAgents/org.solr.plist
  when: ansible_pkg_mgr == 'homebrew'
- name: Start the {{ SOLR_NAME }} launchd service.
  shell: launchctl start org.solr
  when: ansible_pkg_mgr == 'homebrew'
  changed_when: false

- name: "hold until Solr is up and running at http://localhost:{{ SOLR_PORT }}"
  wait_for:
    host: "localhost"
    port: "{{ SOLR_PORT }}"

- name: Check for existing solr configset computate
  shell: "{{ SOLR_OPT }}/server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:{{ ZOOKEEPER_PORT }} -cmd ls /configs/computate"
  ignore_errors: true
  register: SOLR_CONFIGSET_EXISTS
  changed_when: false
- name: Upload computate configset to zookeeper
  shell: "{{ SOLR_OPT }}/bin/solr zk upconfig -n computate -d {{ SOLR_OPT }}/server/solr/configsets/computate -z {{ ZOOKEEPER_HOST_NAME }}:{{ ZOOKEEPER_PORT }}"
  when: SOLR_CONFIGSET_EXISTS.rc != 0

#- name: Setup the solr security configuration
#  template:
#    src: computate_solr_security.json.j2
#    dest: "{{ SOLR_OPT }}/server/solr/security.json"
#- name: Upload security configuration to zookeeper
#  shell: "{{ SOLR_OPT }}/server/scripts/cloud-scripts/zkcli.sh -z {{ ZOOKEEPER_HOST_NAME }}:{{ ZOOKEEPER_PORT }} -cmd putfile /security.json {{ SOLR_OPT }}/server/solr/security.json"
#
#- name: Create computate collection in solr
#  shell: "(SOLR_AUTH_TYPE=basic SOLR_AUTHENTICATION_OPTS='-Dbasicauth={{ SOLR_SOLRJ_USER }}:{{ SOLR_SOLRJ_PASSWORD }}' {{ SOLR_OPT }}/bin/solr create_collection -c computate -n computate)"
- name: Check for existing solr collection computate
  shell: "{{ SOLR_OPT }}/server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:{{ ZOOKEEPER_PORT }} -cmd ls /collections/computate"
  ignore_errors: true
  register: SOLR_COLLECTION_EXISTS
  changed_when: false
- name: Create computate collection in solr
  shell: "{{ SOLR_OPT }}/bin/solr create -c computate -n computate"
  when: SOLR_COLLECTION_EXISTS.rc != 0
